import { CONFIDENCE_SEQUENCES, l, type ConfidenceKey } from './confidence';
import type { TeacherGuide } from './types';

/** These guides describe the lesson workspace, not the separate Story tasks. */
export function confidenceGuide(key: ConfidenceKey): TeacherGuide {
  const sequence = CONFIDENCE_SEQUENCES[key];
  const recovery = {
    'mail-reply': l('A sent reply stays in Sent even if it misses the question. Practice feedback appears only after Check my work. Send a follow-up to correct it. Classroom practice has three received messages.', 'Una respuesta enviada queda en Enviados aunque no conteste la pregunta. Los comentarios aparecen después de Revisar mi trabajo. Envíe otro correo para corregirla. La práctica en clase tiene tres mensajes recibidos.'),
    'mail-attach': l('The app allows the wrong attachment to be sent. Inspect Sent, then write a follow-up, remove the wrong file, and attach the requested one. A sent message cannot be edited.', 'La aplicación permite enviar un adjunto incorrecto. Revise Enviados, escriba otro correo, quite el archivo incorrecto y adjunte el solicitado. No se puede editar un mensaje ya enviado.'),
    files: l('Students type the recipient’s address. Save applies the selected access even when it is wrong. Reopen Share to inspect people and General access; remove unintended people and keep access Restricted. The home example uses a Google document because Editor access to a PDF does not make it a Google document.', 'El estudiante escribe el correo del destinatario. Guardar aplica el acceso elegido aunque sea incorrecto. Abra Compartir para revisar personas y Acceso general; quite a quienes no correspondan y mantenga Restringido. El ejemplo en casa usa un documento de Google: dar acceso de Editor a un PDF no lo convierte en un documento de Google.'),
    schedule: l('Read the source schedule and request a suitable date and start time. Request sent means awaiting approval; the original schedule has not changed.', 'Lea el horario y solicite una fecha y hora de inicio adecuadas. Solicitud enviada significa pendiente de aprobación; el horario original no cambió.'),
    calendar: l('Use date, start time, and end time controls to propose the whole meeting. A sent proposal remains pending; it does not move the event automatically. The organizer must accept it in a real calendar.', 'Use fecha, hora de inicio y hora de fin para proponer la reunión completa. La propuesta queda pendiente; no mueve el evento automáticamente. En un calendario real, la persona organizadora debe aceptarla.'),
    'account-recovery': l('Enter the fictional email and password, then read the phone messages and enter the code. Incorrect entries remain available to edit. Sign-in checks credentials because that is what a real sign-in service does. The displayed Google sign-in address is accounts.google.com; this is still a simulator.', 'Ingrese el correo y la contraseña ficticios, lea los mensajes del teléfono e ingrese el código. Los datos incorrectos se conservan para editarlos. El acceso comprueba las credenciales, como un servicio real. La dirección de Google mostrada es accounts.google.com; sigue siendo un simulador.'),
    spreadsheet: l('Type directly in the intended cells. This prepared template already contains a total formula. Students email the total and inspect Sent. Observe cell placement as well as the total: swapped values can add to the same amount.', 'Escriba directamente en las celdas indicadas. Esta plantilla ya contiene la fórmula del total. El estudiante envía el total por correo y revisa Enviados. Observe la ubicación de cada valor: valores intercambiados pueden sumar lo mismo.'),
    coursework: l('The deadline is read-only assignment information. Ask students to point to the current deadline; automatic completion does not assess deadline comprehension. Add or create → Google Drive selects a file. Turn in and confirm changes the status to Turned in even for a wrong file. Unsubmit, replace the attachment, and turn in again.', 'La fecha es información de la tarea, no un campo editable. Pida que señalen la fecha actual; la finalización automática no evalúa su comprensión. Agregar o crear → Google Drive selecciona un archivo. Entregar y confirmar cambia el estado a Entregado aunque el archivo sea incorrecto. Anule la entrega, cambie el adjunto y vuelva a entregar.'),
  }[key];
  return {
    skills: [sequence.objective, sequence.evidence],
    prepare: [sequence.timing, sequence.model, l('Choose Classroom practice, Try changed facts, or Home practice. Each is a separate practice attempt using the same app controls. Choose language support separately from computer support.', 'Elija Práctica en clase, Probar con otros datos o Práctica en casa. Cada una es un intento separado con los mismos controles. Elija el apoyo lingüístico por separado del apoyo informático.')],
    stickingPoints: [recovery, l('Check my work is teaching feedback in the Job Card, not a feature of the real app. Real apps check valid addresses and required fields but do not know which attachment or answer a teacher wanted.', 'Revisar mi trabajo es un comentario didáctico en la tarjeta de tarea, no una función de la aplicación real. Las aplicaciones comprueban direcciones y campos obligatorios, pero no saben qué archivo o respuesta pidió el docente.')],
    followUp: [sequence.reflection, sequence.homePractice, sequence.google, l('Use fictional material, school-approved accounts, and a designated practice recipient for real-tool activities. Account-code practice remains simulated. A completed practice count is not evidence of independent mastery.', 'Use material ficticio, cuentas aprobadas por la escuela y un destinatario de práctica designado en las herramientas reales. Los códigos se practican solo en el simulador. Un intento terminado no demuestra dominio independiente.')],
    peerHelp: l('A partner may read or translate source material. Let the learner choose the control, perform the action, and inspect the result. Record the help given separately.', 'Un compañero puede leer o traducir los documentos. Deje que el estudiante elija el control, realice la acción y revise el resultado. Registre por separado la ayuda recibida.'),
  };
}
